// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI-QUW2q5vegcXKI1J0rVw3jV88ADFl5o',
    appId: '1:374544378902:web:8ce61840f919c25016d937',
    messagingSenderId: '374544378902',
    projectId: 'rcbfinal-e7f13',
    authDomain: 'rcbfinal-e7f13.firebaseapp.com',
    storageBucket: 'rcbfinal-e7f13.firebasestorage.app',
    measurementId: 'G-8949ZE05L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzSLwzFU1yi3GtYYUKHj1-0YCFSv7CPQ',
    appId: '1:374544378902:android:022b876259be185616d937',
    messagingSenderId: '374544378902',
    projectId: 'rcbfinal-e7f13',
    storageBucket: 'rcbfinal-e7f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP-QWaBGMJhO19OpBr_GtCedr60Bx7p-M',
    appId: '1:374544378902:ios:d10c6ae5cd3dc58016d937',
    messagingSenderId: '374544378902',
    projectId: 'rcbfinal-e7f13',
    storageBucket: 'rcbfinal-e7f13.firebasestorage.app',
    iosBundleId: 'com.example.robocleaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP-QWaBGMJhO19OpBr_GtCedr60Bx7p-M',
    appId: '1:374544378902:ios:d10c6ae5cd3dc58016d937',
    messagingSenderId: '374544378902',
    projectId: 'rcbfinal-e7f13',
    storageBucket: 'rcbfinal-e7f13.firebasestorage.app',
    iosBundleId: 'com.example.robocleaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI-QUW2q5vegcXKI1J0rVw3jV88ADFl5o',
    appId: '1:374544378902:web:f351e00f30e8d27516d937',
    messagingSenderId: '374544378902',
    projectId: 'rcbfinal-e7f13',
    authDomain: 'rcbfinal-e7f13.firebaseapp.com',
    storageBucket: 'rcbfinal-e7f13.firebasestorage.app',
    measurementId: 'G-P210Q2TZZV',
  );
}
